### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot parse tensor from proto: dtype: DT_FLOAT

### ISSUE THREAD

**Issue by seung-kim** [StanfordVL/GibsonSim2RealChallenge#1]
Hi. When I follow the steps to train the model and excute 'train_locally.sh' I get the following error:

2020-03-03 16:42:53.256081: W tensorflow/core/framework/op_kernel.cc:1628] OP_REQUIRES failed at constant_op.cc:77 : Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 80000
  }
  dim {
    size: 180
  }
  dim {
    size: 320
  }
  dim {
    size: 1
  }
}
float_val: 0

2020-03-03 16:42:53.256131: E tensorflow/core/common_runtime/executor.cc:642] Executor failed to create kernel. Invalid argument: Cannot parse tensor from proto: dtype: DT_FLOAT
tensor_shape {
  dim {
    size: 80000
  }
  dim {
    size: 180
  }
  dim {
    size: 320
  }
  dim {
    size: 1
  }
}
float_val: 0

	 [[{{node TFUniformReplayBuffer/Table_1/zeros_1}}]]
Traceback (most recent call last):
  File "train_eval.py", line 619, in <module>
    app.run(main)
  File "/miniconda/envs/gibson/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/miniconda/envs/gibson/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train_eval.py", line 612, in main
    model_ids_eval=FLAGS.model_ids_eval,
  File "/miniconda/envs/gibson/lib/python3.6/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/miniconda/envs/gibson/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/miniconda/envs/gibson/lib/python3.6/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "train_eval.py", line 439, in train_eval
    rb_checkpointer.initialize_or_restore(sess)
  File "/opt/agents/tf_agents/utils/common.py", line 934, in initialize_or_restore
    self._load_status.initialize_or_restore(session)
  File "/miniconda/envs/gibson/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/util.py", line 908, in initialize_or_restore
    session.run(initializers)
  File "/miniconda/envs/gibson/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/miniconda/envs/gibson/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/miniconda/envs/gibson/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/miniconda/envs/gibson/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot parse tensor from proto: dtype: DT_FLOAT

'test_locally.sh' worked fine. Is there a way to fix this? 

Thanks!

**Comment by fxia22** [comment]
Thanks for your question @seung-kim . I checked and this issue is caused by running too many parallel environments (our default is set to 8) and the training process takes up all the memory. We made some changes and set the default to 2 in our updated docker file. We also made some other changes to make the training easier. 

To update, you can run the following steps:

1. update `gibson_challenge_data` by downloading the data again.
2. `docker pull gibsonchallenge/gibsonv2:latest`,
3. Update with the new commits from this repo: `git pull GibsonSim2RealChallenge`
4. Run `docker build . -t my_submission` and build `my_submission` docker then try again the training code.

**Comment by seung-kim** [comment]
thanks! I tried downloading the data again, but I'm getting 403 forbidden. Could you check the permission on the file please?

**Comment by fxia22** [comment]
sorry, just updated permission.
